# Generated by Django 2.2.28 on 2023-04-22 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'статья блога', 'verbose_name_plural': 'статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 22, 13, 18, 39, 426717), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, unique_for_date='date', verbose_name='Название'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Posts',
        ),
    ]
