# Generated by Django 5.0 on 2023-12-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderstatus_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='color',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
