# Generated by Django 2.2.28 on 2023-04-27 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230427_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарии к статье', 'verbose_name_plural': 'Комментарии к статьям'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 27, 22, 41, 56, 695667), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 27, 22, 41, 56, 697202), verbose_name='Дата комментария'),
        ),
    ]
